server:
  port: 8093

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kikojast3
    username: postgres
    password: fmkaivan


  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true


minio:
  bucket:
    name: kikojast
  default:
    folder: "/"
  access:
    name: minioadmin
    secret: minioadmin

  url: http://127.0.0.1:9000



---
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

---
keycloak:
  realm: kikojast1realm
  auth-server-url: http://localhost:8080
  resource: kikojastclient
  public-client: true
  bearer-only: true